"""Update estimator

Revision ID: 4b692288ce82
Revises: 8f2a69bea15b
Create Date: 2024-10-01 21:04:07.414165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b692288ce82'
down_revision: Union[str, None] = '8f2a69bea15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_detections', sa.Column('events_data_path', sa.String(), nullable=True))
    op.add_column('vehicle_detections', sa.Column('estimation_status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='estimationstatus'), nullable=True))
    op.drop_column('vehicle_detections', 'error')
    op.drop_column('vehicle_detections', 'optical_flow_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_detections', sa.Column('optical_flow_path', sa.VARCHAR(), nullable=True))
    op.add_column('vehicle_detections', sa.Column('error', sa.VARCHAR(), nullable=True))
    op.drop_column('vehicle_detections', 'estimation_status')
    op.drop_column('vehicle_detections', 'events_data_path')
    # ### end Alembic commands ###
