"""First migration

Revision ID: 6b2fd032ae88
Revises: 
Create Date: 2024-08-08 18:45:23.045696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2fd032ae88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('calibration_matrix', sa.JSON(), nullable=False),
    sa.Column('distortion_coefficients', sa.JSON(), nullable=False),
    sa.Column('rotation_matrix', sa.JSON(), nullable=False),
    sa.Column('translation_vector', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_detection_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speed_calibration_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speed_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('calibration_date', sa.DateTime(), nullable=False),
    sa.Column('camera_calibration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_calibration_id'], ['camera_calibrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('video_clip_path', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('LEFT_TO_RIGHT', 'RIGHT_TO_LEFT', name='vehicledirection'), nullable=True),
    sa.Column('estimated_speed', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('true_speed', sa.Float(), nullable=True),
    sa.Column('optical_flow_path', sa.String(), nullable=True),
    sa.Column('speed_calibration_id', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['speed_calibration_id'], ['speed_calibrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_detections')
    op.drop_table('speed_calibrations')
    op.drop_table('live_detection_state')
    op.drop_table('camera_calibrations')
    # ### end Alembic commands ###
