"""Add croppign

Revision ID: 7ece8ef77c75
Revises: 4b692288ce82
Create Date: 2024-10-06 13:53:06.630749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ece8ef77c75'
down_revision: Union[str, None] = '4b692288ce82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speed_calibrations', sa.Column('left_crop_l2r', sa.Integer(), nullable=True))
    op.add_column('speed_calibrations', sa.Column('right_crop_l2r', sa.Integer(), nullable=True))
    op.add_column('speed_calibrations', sa.Column('left_crop_r2l', sa.Integer(), nullable=True))
    op.add_column('speed_calibrations', sa.Column('right_crop_r2l', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speed_calibrations', 'right_crop_r2l')
    op.drop_column('speed_calibrations', 'left_crop_r2l')
    op.drop_column('speed_calibrations', 'right_crop_l2r')
    op.drop_column('speed_calibrations', 'left_crop_l2r')
    # ### end Alembic commands ###
